dist: trusty
sudo: true

language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - asciidoc

install:
  - pip install -r requirements.txt

script:
  - make html
  - touch output/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "output"
  target_branch: "master"
  on:
    branch: blog
