= How did I get here?
:date: 2017-08-19 21:00
:category: story-time

It's one of those question that I often ask myself personally, How did I get
here. How did I became a maintainer for two organizations, How did I get a
freelancing job for a startup in Germany, How did I win Google Code-In,
and Who am I before living inside a text editor from the 70s?

Well, I can be really annoying and just say "I don't know". Because, I really
don't know. It's not an easy question and it's not the one where there's only
one answer.

We have to start somewhere I guess, so.. hmm.

Let me start by what makes me interested with Computers. Why am I wasting a
lot of time inside my home in a dark room with a keyboard and a screen to
fill the room.

It was around 2006, my family just moved to a new home and after a while my dad
got home and he brought a bunch of boxes, it was a lot of boxes in various
sizes. My dad was assembling something, well I'm not sure because most likely
I just sleep and gaze myself to the television.

The next morning, I saw a blue table on top of it is a bulky box that looks like
a TV, a thing with a lot of buttons, small curvy thing with a ball inside of it,
and lasty a tower painted black with silver buttons that electrocutes me every
time I press it.

Well, It's a computer, my dad introduced me to it shortly and my memories are
fuzzy so I'm not sure what happened. After a while, I got hooked... on games
that were installed. It ran Windows 98 Second Edition and the game that I always
play on it was Daytona USA, Virtual Cop, and Tarzan. I don't know the
specifications of the computer. Hell, I don't know what a processor is and a
common misconception is I called the tower the "CPU" which is well, wrong.

Anyway, after a while, I got it running Windows XP and we had to move to my
grandma's house because my parents wanted to renovate the house. During my stay
at my grandma's, my dad brought me to this place where they sell a lot of CDs.
Well, we grabbed a bunch of games and the store offered me some free software
because we bought a lot of things, sure I wanted it. To my surprise, my dad
specifically picked this one green CD titled "Mandriva 2006". I didn't know what
it was back then, on the back cover it has pictures of penguins and on the front
cover it has a picture of a penguin. I remember gazing on the cover during the
ride back home, I wonder what it was.

When we got home, my dad installed it on my computer and introduced me to it. It
was there, KDE 3. I still remember the stuff that I like about it even to this
day I still remember how cool and customizable it is. The popular skeumorphism
look just was really appealing back then. I remember try and see what every
single button does. I even notice this thing called "root", when I asked my dad
what it is and what's with the background which is a tile of bombs, he replied
with "don't use it your computer will explode". Looking at back it, I think he
just want me to not break the system, but back then I was scared and kept myself
away from it.

I also remember trying out SUSE Linux (before it was called openSUSE) after my
dad introduced me to this magazine called "InfoLinux" and Ubuntu after the house
renovation is done.

I was an odd kid back then, I was still a cry-baby, I don't know how everything
worked back then, and I usually find myself interested in odd and unfamiliar
things, like computers. It wasn't a common thing in Indonesia back in the day,
unlike in western countries where it's normal for kids to use a computer and
use the Internet. It wasn't common back then, Internet was a thing for people
who have a lot of money and dial up was the choice for most people. I still
remember the advertisement for Telkom's old Dial-up service. I remember that
I was intrigued looking at ad where a telephone line is plugged into a laptop
and they have to dial this number. Well, I always wondered what the Internet is
back in the day. I remember my dad used to connect to the Internet with a some
sort of USB Modem. I don't know what it was, but I remember I found out it's a
USB Bluetooth and he probably connected it to his phone.

While writing this, I don't have a clear timeline of my life. I didn't bother
to write a diary back then. So stuff will most likely mixed up but I do have a
clear timeline on some memorable moments but I remember them not on age but on
what grade of school I'm on.

Anyway, I was an odd kid back then, I remember on the third grade me with a
couple of friends sitting and talking to each other... about how people kill
themselves at this building that we looked at. Yes, I find it to be an odd topic
as well and my parents would worried about me.

On my 8th birthday, my dad got me a new computer. An Intel Core 2 Duo machine
with a whopping 2GB of RAM and an NVIDIA GeForce. I was suprised and happy. I
remember my dad teased me about an Intel Core 2 Duo PC on Ramadhan. It had
Ubuntu installed, I think it was 6.04 and Windows XP. Also, my dad installed
Compiz. Which is this magical box of desktop effects. I remember playing with it
for a long time. Desktop cubes, wobbling windows, etc. Enabling and playing with
every single effect. It was fun.

After a while, my dad got Internet installed. Sweet, I remember after installing
when testing the Internet, the guy opened YouTube and a Tom and Jerry video. I
was like what's this?. My mom was worried about it though because she thought it
may have porn on it. Well, I didn't listen because I was interested. I remember
she used to watch a lot of ghost videos but what I usually watch is a lot of
tech videos. Like people running old versions of Windows on computers or consoles
running Ubuntu or homebrew and a lot of stuff. I remember the notepad videos and
the infamous Trance - 009 Sound System Dreamscape. A lot of people got annoyed
with the sond, but I like it. Anyway, YouTube is also the reason why I got
interested in this the electronics genre of music. Back then, I remember listening
to Daft Punk. I remember while going back home from School, my friends were having
a quiz about music artists and I mentioned Daft Punk. They didn't know about it and
thought I was making stuff up. Well, I like Daft Punk a lot back then, even today I
still find their songs to be really good.

Anyway, I think I was at the 9th grade that I started playing with Visual Basic. I
remember that I had VB 6.0 back in the day, it was like 2006 but I'm really not
sure when because I had Linux installed and I know I had Windows XP before and after
it, but really I'm not sure. Anyway, I remember playing around with the program and
started doing some crappy Internet browser, a crappy "OS" which is really just a
shell. I still know it's "programming" but I didn't know how to program, what I did
is just placing buttons and other GUI components and played around with the
properties and I did some tutorials from YouTube videos. Most of the time I just
copy-paste code and see what it does. From there, like most people with old 80s
BASIC games book, I know a bit of Visual Basic.

On the 5th grade, my dad got me into a Java course at Nurul Fikri. More on that
later.

Another thing that I have problems with is telling stories parts of my life.
It's the feeling of I don't want to miss stuff but I have to or it'll be really
really long. I remember on a trip a teacher wanted me to tell the other students
on how I won GCI and it ended up being 30 mins long. Well, yeah. I'm not a good
speaker without something like slides or notes to limit my scope. Anyway, on this
blog post I can have the audacity to list them all and make this long, but I don't
want to. Because it'll be days to write and will have more words than your usual
Russian novel.

More on Part 2(?). I don't know when that will happen because it's pretty rare for
me to have time.

Anyway, Thanks for reading this long post.
